### ISSUE TITLE
No adding or removing in Rails 3?

### ISSUE THREAD

**Issue by sscirrus** [ryanb/complex-form-examples#10]
Hi Ryan,

I've tried to incorporate this example into an app I've got running on Rails 3 but adding and removing fields are not working at all (the data does save properly). It is not permitting the view to contain <%= remove_child_link "remove", f %> at all. The error message here is: Model does not respond to _delete. Once I remove this code, it produces the view but clicking either of my 'add fields' buttons does nothing. Have you come across this issue before in Rails 3?

**Comment by rywall** [comment]
Use _destroy instead

**Comment by sscirrus** [comment]
Thanks a lot rywall, it did work. I'm still having issues with add_child_link. I have this exact code in the application_helper: https://github.com/ryanb/complex-form-examples/blob/deep/app/helpers/application_helper.rb

I have this line in my _assignment.html.erb partial: <%= add_child_link "Add Step", f, :steps %>.

Clicking the link has no effect at all - it just adds a # to the url. Is there something I need to check for? This is for Rails 3.

**Comment by piedpipes** [comment]
sscirrus I am having the same problem. Can anyone shed any light on how we can test for what's happening here?

**Comment by sscirrus** [comment]
Thanks a lot rywall - this solved the problem!

**Comment by DennisFiore** [comment]
Could you please explain what fixed the issue? I have not been able to figure it out.
I too am using Rails 3.

**Comment by ryanb** [comment]
I have updated the repository to a Rails 3 application. See if that's working for you.
