### ISSUE TITLE
Child_fields not associating to the right parent

### ISSUE THREAD

**Issue by sscirrus** [ryanb/complex-form-examples#12]
Hi guys,

I have been wrestling with this problem for a very long time (days) and I would really appreciate your help. I have been using the unobtrusive-JQuery-deep branch to build a form with 3 nested levels. Let's say they are Levels 1, 2, and 3 (where 1 has_many 2s, 2 has_many 3s).

Click "add #3" and the child_fields that are created associate themselves with the first #2 every time. I checked the html of the new fields and their association 'index' next to 2 is always 0. So, upon saving, every #3 generated attaches itself to the first #2.

My application helper is literally identical to the unobtrusive-JQuery-deep code. I really need to fix this! Thank you.

---

This is an assignment that already existed for the 2nd task in my form:
`project[tasks_attributes][1][assignments_attributes][1][assignment]`

This is an assignment generated for the 2nd task in my form:
`project[tasks_attributes][0][assignments_attributes][1296710544742][assignment]`

**Comment by sscirrus** [comment]
More detail - I just did some more digging and found that the child_fields_templates that are hidden in the form DO appear to be correct. Something is getting screwed up when they are actually rendered.

Here's the hidden named inputbox for the 2nd task's assignment:
`project[tasks_attributes][1][assignments_attributes][new_assignments][assignment]`

**Comment by ryanb** [comment]
Closing this because I am not supporting the unobtrusive-jquery-deep branch. I have updated the repository to a Rails 3 app and archived the previous branches into a `rails2` branch. I will work on adding a new unobtrusive jQuery solution soon.

**Comment by afast** [comment]
This still seems to be an issue with rails 3.2.8 and nested_form branch
