### ISSUE TITLE
Some changes for jquery

### ISSUE THREAD

**Issue by davidslvto** [ryanb/complex-form-examples#14]
Hi,

We did some changes to application.js for jquery

``` javascript
function remove_fields(link) {
  $(link).prev().val("1");
  $(link).parent().parent().hide();
}

function add_fields(link, association, content) {
  var new_id = new Date().getTime();
  var regexp = new RegExp("new_" + association, "g")
  $(link).prev().after(content.replace(regexp, new_id));
}
```

**Comment by ryanb** [comment]
Thanks, it looks like this is still fairly strict and dependent upon where the add/remove link is placed in the DOM tree. If you change the DOM structure you'll need to change the jQuery to reflect this. If someone has a suggestion of some jQuery which is not so strict on the structure please post here and I'll reopen.

**Comment by martinsamek** [comment]
Hi

How to implement function add_fields in mootools ???
