### ISSUE TITLE
Small change to "add" and "remove" links

### ISSUE THREAD

**Issue by wcmartin** [ryanb/complex-form-examples#2]
Hi, I used the deep nesting form as an example to work from and it was very helpful.  I made two small changes on my implementation.  One, I changed the return of the add_child_link function from

 "<ahref=\"#\" onclick=\"#{h(js)}\">#{name}</a>" 

to

 link_to_function(name, h(js))

This way the page doesn't scroll to the top of the window every time the link is pressed.

The other change was I changed the remove check boxes into link's that perform javascript to remove the appropriate fields.  I also had to "mark them for destroy" with javascript / virtual attributes, similar to what was done in the rails cast on complex forms.  I'm not sure if this was the right thing to do as I'm relatively new to rails, but perhaps it's a matter of preference on form design. Thanks!

**Comment by ryanb** [comment]
That's right, I forgot to return false on the javascript. I'm actually surprised you got `link_to_function` working, I tried every other combination of escaping and guess I missed that one. Will update code soon.

As for the remove link, I plan to implement this in another branch soon. You can do this without adding a virtual attribute (using the _delete attribute).

**Comment by ryanb** [comment]
This has been fixed. Check out the remove-link branch for a solution on that.

I'll likely merge the remove-link and deep branches into master soon once I get the functionality polished.
