### ISSUE TITLE
Deeply nested forms and escaping javascript

### ISSUE THREAD

**Issue by mikezaschka** [ryanb/complex-form-examples#3]
First of all thank you for posting you solution. 
It does work very well  in a two level form, but I've got problems using it in a deeper nested form. 
Firebug gives me a javascript error if I want to put an "add_child_link" into another added partial. There seems to be a escaping bug.

I already tried to avoid escaping the inner partial by passing another option to the link function (:already_escaping => true), but this somehow doesn't work.

Any hints on that?

Best regards,

Mike

**Comment by ryanb** [comment]
Are you using the "deep" branch for testing? Also make sure you are using the latest commit. I'm unable to reproduce this with FireFox 3.5.2.

**Comment by mikezaschka** [comment]
It actually does work!
I used my one little javascript snippet which looked like yours... but it had some tiny little difference which broke it.

I replaced it with yours... and now it works like a charm!

Sorry for bothering you and thanks for this working example (and the awesome screencasts)!
