### ISSUE TITLE
jQuery & Unobtrusive JavaScript

### ISSUE THREAD

**Issue by ryanb** [ryanb/complex-form-examples#6]
Add a branch for unobtrusive JavaScript with jQuery. Consider using it for the primary solution. See Tim Riley's fork and post for details.

http://github.com/timriley/complex-form-examples
http://openmonkey.com/articles/2009/10/complex-nested-forms-with-rails-unobtrusive-jquery

_Make sure to test this for deeply nested associations._

**Comment by alloy** [comment]
Looking forward to the results. If this is merged, I'm also gonna remove my fork of the repo, as people may think they should use my basic example. Which only was to illustrate ‘it works’ in the first case.

**Comment by ryanb** [comment]
One issue I've come across with this solution is that the new fields template is still submitted through the form. Therefore if you remove this from the `accepts_nested_attributes_for` call...

<pre>:reject_if => lambda { |a| a.values.all?(&:blank?) }</pre>


Then it will attempt to create a model for the new fields. One solution would be to move template outside of the form entirely, but then you do not have easy reference to the form builder which becomes an even bigger problem for deeply nested models. Any ideas?

**Comment by ryanb** [comment]
You can see the work I've done so far on `unobtrusive-jquery` and `unobtrusive-jquery-deep` branches. The latter currently does not work due to the problem mentioned above.

**Comment by timriley** [comment]
Hey guys,

I've made 2 different fixes for this problem.
1. Modify the :reject_if condition to only consider the real attributes of the nested object only. It will ignore blank attributes of that nested object's children.
2. Move the child field templates outside of the form. They will only appear once each, at the end of the form. This is more efficient (only one instance of each hidden template div), but then you lose the context of all the generated IDs in the name attribute of each input element. I added some JavaScript to ensure that these are inserted when clicking "new child". This approach doesn't require any reject_if condition in the model.

These are available at http://github.com/timriley/complex-form-examples/tree/unobtrusive-jquery-deep-fix1 and http://github.com/timriley/complex-form-examples/tree/unobtrusive-jquery-deep-fix2 respectively.

What do you think?

**Comment by timriley** [comment]
I just updated the javascript in my unobtrusive-jquery-deep-fix2 branch to make the form work properly when editing previously existing projects: http://github.com/timriley/complex-form-examples/tree/unobtrusive-jquery-deep-fix2

**Comment by ryanb** [comment]
I've added a nested_form branch which uses the nested_form gem for unobtrusive javascript.
