### ISSUE TITLE
Remove link for multiple fields

### ISSUE THREAD

**Issue by ryan8720** [ryanb/complex-form-examples#7]
Hi,

Thanks for this great example.

I'm using this in my application, but it displays three text_fields when you click the Add link.  This works fine, except the remove link won't work for more than one field. How can I fix this?

Thanks!

**Comment by ryanb** [comment]
Does the example application here work properly for you? If so then there must be some difference between the example application and your application which is causing these bugs. It's hard for me to say what that could be.
