### ISSUE TITLE
Sorting child elements & inserting children at any position?

### ISSUE THREAD

**Issue by jensb** [ryanb/complex-form-examples#9]
Hello,

I would like to implement the above features. By patching add_child (.js) and the helper functions, I have successfully managed to create a form which can insert a new child element at any position between existing children in the form. However, no amount of hackery (replacing IDs, form names, the numbers in the form names (e.g. the "45" in parent[child][45][attrib_name]) helps me with the problem that Rails, server-side, still considers the inserted element the "last" element, no matter in which order it occurs in the HTML and/or HTTP-POST hash.

How does Rails determine the order of children? Is it possible to define (and redefine) this order client-side? My child elements already have an attribute "position", and I can update this attribute when successfully saving parent and child elements, but it does not work when validation errors occur (then Rails will repopulate the child elements in the wrong order).

Any ideas would be greatly appreciated! I will then open a Github repo and share the code.

Thanks

Jens

**Comment by jensb** [comment]
I have solved this in principle. I can now insert children at any -fixed- position. It is somewhat hackish but it works. If you want a patch, I can send it to you.

**Comment by sscirrus** [comment]
Hi Jen,

I'd love to see that patch if you wouldn't mind sending it to me. I've been having some serious problems getting newly-inserted children to tie to the right parent - I'm also trying to get some ordering working. Thank you.

SSCirrus

**Comment by jensb** [comment]
I will try to fork these examples ASAP. Sorry for the delay.

**Comment by jensb** [comment]
PS: both inserting at any position and ordering is solved, including handling validation errors and re-POSTing. No model or controller modification necessary, it is all Javascript and a "position" column for child elements.

**Comment by jensb** [comment]
Hi,
I'm sorry I didn't get back to you yet. if I send you patches, will you fork the complex-form-examples and integrate them? I cannot find the time right now.
